### ISSUE TITLE
you need design a shortcut

### ISSUE THREAD

**Issue by Louis-udm** [sidmishraw/topper#1]
you need design a shortcut

**Comment by sidmishraw** [comment]
Did you mean something like a keyboard shortcut? If you want a keyboard shortcut, you can bind the `topper.addTopHeader` command to the key combination of your choice.

> Note: The command name is `topper.addTopHeader` starting from v0.0.3. Former versions had `extension.addTopHeader`.

**Comment by Louis-udm** [comment]
but there is a difficulty in using it. We have to take a few steps:
1. cmd + shift + p
2. tap topper, tap enter
3. click "information: xxxxxx xxxx "
4. click personalProfile or officeProfile.

in my opinion, if we can bind a shortcut with personalProfile ou officeProfile, and we press the shortcut, and the comment of personalprofile displays immediately.

**Comment by Louis-udm** [comment]
I know only install plugin in vs code. can you update the version on database of  vs code?

**Comment by sidmishraw** [comment]
Sure. That makes more sense. I'll start working on it soon.

**Comment by Louis-udm** [comment]
thanks

**Comment by Louis-udm** [comment]
and a problem:
when we modified the code, the "last-modified" in the comment can not update.

**Comment by Louis-udm** [comment]
an idea more simple:
you can design a function for bind a shortcut, it apply only the first template, this is more simple for your work.

**Comment by sidmishraw** [comment]
@Louis-udm I needed your opinion on something I was thinking about. Suppose I introduce a new style of command for you to bind custom keys. For example, if you have a profile named `officeProfile`, you can assign custom keybinding to a command like `topper.officeProfile`.
Does this make it easy to use?

**Comment by sidmishraw** [comment]
I have added profile specific commands. Using these, you can achieve profile specific custom keybindings. For example, to define a custom keybinding for your `officeProfile`, you can define a keybinding in the `keybinding.json` as:
```json
{
  "key": "cmd+shift+t",
  "command": "topper.addTopHeader.officeProfile"
}
```

When you press the key combination, Topper will generate the header for the `officeProfile`profile.

> Note: This feature is available from v0.2.0 onwards.

**Comment by Louis-udm** [comment]
This sounds great!
update it to the database official please, I can not wait to try.

Do you repaired the problem that the "last-modified" in the comment can not update ?

**Comment by Louis-udm** [comment]
Do you repaired the problem that the "last-modified" in the comment can not update ?

**Comment by sidmishraw** [comment]
@Louis-udm The new version of topper (v0.2.0) is available on the VScode marketplace (the marketplace takes some time to validate the extensions before making them open to public).

As for the "last-modified" issue, I'm opening another GitHub issue to track it. You can follow the issue [#2] for the updates.

Thanks for using topper :)

**Comment by Louis-udm** [comment]
great

**Comment by Louis-udm** [comment]
Thank you too
