### ISSUE TITLE
 How to change the default header template for all languages?

### ISSUE THREAD

**Issue by billowz** [sidmishraw/topper#11]

**Comment by sidmishraw** [comment]
The default header for all languages has not been externalized.

**Comment by sidmishraw** [comment]
I've added a new configuration in topper version 1.1.0 called `topper.defaultHeaderTemplate`. By configuring this configuration you can modify the default header template for all the languages that don't have a custom header template defined yet. Make sure that you don't change the language ID of the default header template –– it has to be `default`.
