### ISSUE TITLE
last-modified  update 

### ISSUE THREAD

**Issue by shaooping** [sidmishraw/topper#13]
First, thank you, this is a very nice tool.
And there have a problem I need your help:

About the date format, the default date format like this :
# @created-time : 2019-10-26T10:23:23.690Z+08:00
# @last-modified: 2019-10-30T08:39:21.713Z+08:00

Now I want to change it form like this:
# @created-time : 2019-10-26 10:23:23
# @last-modified: 2019-10-30 08:39:21

I have changed the date format and lastModifiedRegex, but when I saved the file, last-modified doesn't update.
So I what to know which file should I need to modify?
Isn't the file path: sidmishraw.topper-1.2.0/out/src/topper/topper.js?
Looking for your reply, thans again.

**Comment by sidmishraw** [comment]
Are you trying to define the custom date format for use with the extension or the code of the extension?

**Comment by shaooping** [comment]
> Are you trying to define the custom date format for use with the extension or the code of the extension?

Yes,thanks, I hope the form like this and when save file ,the last-modified will change  : 
@created-time : 2019-10-26 10:23:23
@last-modified: 2019-10-30 08:39:21

I have read the readme.md but can not understand which file I should change.

**Comment by sidmishraw** [comment]
Okay got it.
Follow the steps below to add a custom date format:
1. Open VS Code preferences menu and open the `settings.json`.
2. In the `settings.json` file, you need to add the following properties:
  a. "topper.dateFormat": "<your format here>"
  b. "topper.lastModifiedRegex": "<your updated regex here>"

Then reload the window for VS Code and then extension will load the updated settings. With this you should be able to use your custom date format for created and last modified fields.

**Comment by shaooping** [comment]
Very nice, thank you, it's work. I did not notice that >--File->>-Preferences->>Settings, then use the search setting bar find topper, and change the ”topper.dateFormat ” and “topper.lastModifiedRegex” directly.
Then I find that the setting.json also has changed.
Here my change:
    "topper.dateFormat": "YYYY-MM-DD HH:mm:ss",
    "topper.lastModifiedRegex": "[ ]*\\@last\\-modified\\s*.?\\s+((\\d{4}-\\d{2}-\\d{2})\\s(\\d{2}:\\d{2}:\\d{2}))\\n*",
The head:
# @created-time : 2019-10-26 10:23:23
# @last-modified: 2019-10-30 18:25:46
When I press Ctrl s, the time has changed.
Okay, thanks again, best wishes!

**Comment by sidmishraw** [comment]
Cool. Thanks for using topper :)
