### ISSUE TITLE
I want to join the insert line specification

### ISSUE THREAD

**Issue by dayhi** [sidmishraw/topper#7]
希望加入插入行指定
I want to join the insert line specification

例如php需要在第二行插入
For example php needs to be inserted in the second line

**Comment by sidmishraw** [comment]
Hey @dayhi, could you please give me an example. Like a final form of the header you're expecting.

**Comment by dayhi** [comment]
[Example](https://github.com/OBKoro1/koro1FileHeader/wiki/%E9%85%8D%E7%BD%AE#3-%E5%A4%B4%E9%83%A8%E6%B3%A8%E9%87%8A%E7%AC%AC%E5%87%A0%E8%A1%8C%E6%8F%92%E5%85%A5)


He added this feature in [ v3.2.0（code）](https://github.com/OBKoro1/koro1FileHeader/commits/master), but his customization is not as good as yours.

**Comment by dayhi** [comment]
@sidmishraw

**Comment by sidmishraw** [comment]
@dayhi it will be done. I hope you already have a workaround when using topper. If not, I'd recommend you add the template for php as:

```javascript
{
    php: {
      headerBegin: "<?php\n/*",
      headerPrefix: "*",
      headerEnd: " */\n?>",
      template: [
        "${headerBegin}",
        "${headerPrefix} ${fileName}",
        "${headerPrefix} @author ${author}",
        "${headerPrefix} @description ${description}",
        "${headerPrefix} @created ${createdDate}",
        "${headerPrefix} @last-modified ${lastModifiedDate}",
        "${headerEnd}"
      ]
    }
  }
```

You have the ability to define your own header begin, header-end, and header-prefixes.

P.S. Thanks for using topper.

**Comment by dayhi** [comment]
ok，thanks
