### ISSUE TITLE
How could change the type of date?

### ISSUE THREAD

**Issue by Wanger-SJTU** [sidmishraw/topper#9]
I want to insert the data type like `2019-3-15`, is this suportted?

**Comment by sidmishraw** [comment]
Date formatting is not supported yet. The most recent updated datetime and created datetime are in the standard format.

**Comment by sidmishraw** [comment]
Look forward to the next release, I've externalized the date formatting and last modified date replacement capture regex in the upcoming release. So, it should be possible to format the created date and modified date values. Defaults to ISO format.

**Comment by Wanger-SJTU** [comment]
thx
